# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Aplicación
    url: https://app.fluxbound.es
  - name: API
    url: https://api.fluxbound.es
    expectedStatusCodes:
      - 404

status-website:
  cname: status.fluxbound.es
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /

i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
