#
owner: Fluxbound
repo: fluxbound-status-page

sites:
  - name: Web
    url: https://app.fluxbound.es
  - name: API
    url: https://api.fluxbound.es
    expectedStatusCodes:
      - 404
  - name: VPN
    check: "tcp-ping"
    url: $VPN_IP
    port: $VPN_PORT

status-website:
  cname: status.fluxbound.es
  themeUrl: https://status.fluxbound.es/fluxbound.css
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Fluxbound
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: Incidentes Activos
  allSystemsOperational: Todos los sistemas están operativos
  incidentReport: "Reporte de incidente #$NUMBER →"
  activeIncidentSummary: Abierto el $DATE con $POSTS posts
  incidentTitle: Detalles del incidente $NUMBER
  incidentDetails: Detalles del incidente
  incidentFixed: Solucionado
  incidentOngoing: En progreso
  incidentOpenedAt: Abierto el
  incidentClosedAt: Cerrado el
  incidentViewOnGitHub: Ver y suscriberse en GitHub
  incidentCommentSummary: Publicado el $DATE por $AUTHOR
  incidentBack: ← Volver a todos los incidentes
  pastIncidents: Incidentes Pasados
  pastIncidentsResolved: Resuelto en $MINUTES minutos con $POSTS posts
  liveStatus: Estado actual
  overallUptime: "Uptime general: $UPTIME"
  overallUptimeTitle: Uptime general
  averageResponseTime: "Tiempo de respuesta promedio: $TIMEms"
  averageResponseTimeTitle: Tiempo de respuesta promedio
  sevelDayResponseTime: Tiempo de respuesta a 7 días
  responseTimeMs: Tiempo de respuesta (ms)
  up: Correcto
  down: Caído
  degraded: Degradado
  ms: ms
  loading: Cargando
  navGitHub: GitHub
  footer: Powered by [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Número de solicitudes excedido.
  rateLimitExceededIntro: Has superado el número de solicitudes que puedes realizar en una hora, por lo que tendrás que esperar antes de volver a acceder a este sitio web. Como alternativa, puedes añadir un token de acceso personal de GitHub para seguir utilizando este sitio web.
  rateLimitExceededWhatDoesErrorMean: ¿Qué significa este error?
  rateLimitExceededErrorMeaning: Este sitio web utiliza la API de GitHub para acceder a datos en tiempo real sobre el estado de nuestros sitios web. Por defecto, GitHub permite 60 solicitudes por hora a cada dirección IP, las cuales ya ha consumido.
  rateLimitExceededErrorHowCanFix: ¿Cómo puedo solucionarlo?
  rateLimitExceededErrorFix: Puedes esperar una hora más y se restablecerá el límite de tu dirección IP. Como alternativa, puedes añadir tu token de acceso personal de GitHub, que te da 5000 solicitudes adicionales por hora.
  rateLimitExceededGeneratePAT: Aprende a como generar un Token de Acceso Personal
  rateLimitExceededHasSet: Tienes un token de acceso personal configurado.
  rateLimitExceededRemoveToken: Borrar token
  rateLimitExceededGitHubPAT: Token de Acceso Persona a GitHub
  rateLimitExceededCopyPastePAT: Copia y pega tú token
  rateLimitExceededSaveToken: Token de guardado
  errorTitle: Se ha producido un error.
  errorIntro: Se ha producido un error al intentar obtener los detalles del estado más reciente.
  errorText: Puedes intentarlo de nuevo en unos minutos.
  errorHome: Ir al inicio
  pastScheduledMaintenance: Mantenimientos Programados Pasados
  scheduledMaintenance: Mantenimiento Programado
  scheduledMaintenanceSummaryStarted: Empezado el $DATE durante $DURATION minutos
  scheduledMaintenanceSummaryStarts: Empieza el $DATE durante $DURATION minutos
  startedAt: Empezado el
  startsAt: Empieza el
  duration: Duración
  durationMin: $DURATION minutos
  incidentCompleted: Completado
  incidentScheduled: Programado
  duration24H: 24h
  duration7D: 7d
  duration30D: 30d
  duration1Y: 1a
  durationAll: todo
  locale: es-es
  
